### ISSUE TITLE
Issue when testing for multiple media queries

### ISSUE THREAD

**Issue by peterramsing** [ryanbahniuk/sassaby#25]
I am struggling to test whether or not a second media query is created within a mixin.

**This may be user error, so please let me know if I'm testing this incorrectly.**

I'm working on getting this working and will get a PR together if I'm able to figure something out.

Here's the scss:

``` scss
@mixin helper--center-image-outside-bounds(
    $max-width,
    $medium-max-width: null,
    $large-max-width: null
    ) {

    left: 50%;
    margin-left: margin-left-math($max-width);
    max-width: $max-width;
    overflow: hidden;
    position: relative;

    @if $medium-max-width {
        @media #{$tablet} {
            margin-left: margin-left-math($medium-max-width);
            max-width: $medium-max-width;
        }
    }

    @if $large-max-width {
        @media #{$desktop} {
            margin-left: margin-left-math($large-max-width);
            max-width: $large-max-width;
        }
    }
}
```

I am able to test whether or not the first media query is created when both are created but because [L86](https://github.com/ryanbahniuk/sassaby/blob/master/src/parsers.js#L86) of `parsers.js` only passes the first (`0`) value of the array I'm unable to determine if the second media query was created.

Here's the test:

``` js
...
it("Creates a media query when large size is declared", function() {
     sassaby.includedMixin('helper--center-image-outside-bounds').calledWithArgs('1000px', '2000px', '3000px').createsMediaQuery('(min-width: 900px)');
});
...
```
